# Generated by Django 3.2.8 on 2021-10-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0002_alter_items_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
