# Generated by Django 3.2.8 on 2021-10-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0003_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
